version: "3.8"
services:
  envoy:
    network_mode: host
    image: envoyproxy/envoy:v1.17-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command:
      - "-l debug"
      - "-c /etc/envoy/envoy.yaml"
