#syntax=docker/dockerfile:experimental

FROM dlunch/rust:1.50.0-stretch as builder

RUN rustup component add rustfmt
RUN apt-get update && apt-get install protobuf-compiler libpq-dev -y

WORKDIR /src

COPY . .
RUN --mount=type=cache,target=/src/target cargo install --path server --locked --bins --root build

FROM debian:stretch-slim
COPY --from=builder /src/build/bin /server

RUN apt update -y && apt install libssl1.1 libpq5 -y && rm -rf /var/lib/apt/lists/*

ENTRYPOINT "/server/server"
