version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
  envoy:
    image: envoyproxy/envoy:v1.17-latest
    ports:
      - 8000:8000
    volumes:
      - ./docker/envoy.yaml:/etc/envoy/envoy.yaml
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
