version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - LISTEN_ADDR=0.0.0.0:9090
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - TOKEN_SECRET
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        GRPC_HOST: 'http://localhost:8000'
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  envoy:
    image: envoyproxy/envoy:v1.17-latest
    ports:
      - 8000:8000
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - server

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
