version: "3.8"
services:
  server:
    build: .
    ports:
      - 9090:9090
  envoy:
    image: envoyproxy/envoy:v1.17-latest
    ports:
      - 8080:8080
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
