FROM ubuntu:focal

RUN apt update && apt install -y curl socat
RUN curl -O https://safetx.ahnlab.com/master/linux/astx_u64.deb
RUN DEBIAN_FRONTEND="noninteractive" apt install -y ./astx_u64.deb
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /
COPY . .

# astx
EXPOSE 55920:55930
ENTRYPOINT ["/scripts/astx.sh"]