FROM ubuntu:focal

RUN apt update && apt install -y curl socat libxml2 libnfnetlink0 libnetfilter-conntrack3 libglib2.0-0 && rm -rf /var/lib/apt/lists/*
RUN curl -O https://safetx.ahnlab.com/master/linux/astx_u64.deb
RUN dpkg --force-all -i ./astx_u64.deb

WORKDIR /
COPY . .

# astx
EXPOSE 55920:55930
ENTRYPOINT ["/scripts/astx.sh"]