[package]
name = "server"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "^1.7", default-features = false, features = ["tokio02", "attributes"] }
dotenv = { version = "^0.15", default-features = false }

scrap = { path = "../scrap" }