[package]
name = "server"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"

[dependencies]
fantoccini = { version = "^0.16", default-features = false }
webdriver = { version = "^0.43", default-features = false }
async-std = { version = "^1.7", features = ["tokio02", "attributes"] }
serde_json = { version = "^1.0", default-features = false }
dotenv = { version = "^0.15", default-features = false }
maplit = { version = "^1.0", default-features = false }
async-trait = { version = "^0.1", default-features = false }